interface Macro {
  id: string;
  uid: string;
  name: string;
  url: string;
  screenshotUrl: string;
  scheduleFrequency: number;
  scheduleHour: number;
  scheduleMinute: number;
  scheduleSunday: Boolean;
  scheduleMonday: Boolean;
  scheduleTuesday: Boolean;
  scheduleWednesday: Boolean;
  scheduleThursday: Boolean;
  scheduleFriday: Boolean;
  scheduleSaturday: Boolean ;
  notifySuccess: boolean;
  notifyFailure: boolean;
  checkEntirePage: boolean;
  checkSelectedArea: boolean;
  isEntirePageUpdated: boolean;
  isSelectedAreaUpdated: boolean;
  isFailure: boolean;
  userAgent: string;
  acceptLanguage: string;
  viewportHeight: number;
  viewportWidth: number;
  deviceScaleFactor: number;
  selectedAreaLeft: number;
  selectedAreaRight: number;
  selectedAreaTop: number;
  selectedAreaBottom: number;
  events: MacroEvent[];
  histories: MacroHistory[];
  createdAt: FirebaseFirestore.Timestamp;
  updatedAt: FirebaseFirestore.Timestamp;
  executedAt: FirebaseFirestore.Timestamp;
}
